#!/bin/bash

target="/dev/null"
excludes=""

# Resets the above variables
source /etc/backup.conf

date=$(date "+%Y%m%dT%H%M%S")
sudo rsync \
	--archive \
	--link-dest="${target}/current" \
	--delete \
	--delete-excluded \
	--exclude="/dev" \
	--exclude="/sys" \
	--exclude="/tmp" \
	--exclude="/proc" \
	--exclude="/mnt" \
	--exclude="/media" \
	--exclude="/run" \
	--exclude="*.pyc" \
	--exclude="/home/*/.cache" \
	--exclude="/home/*/.gvfs" \
	--exclude="/home/*/.vagrant.d" \
	--exclude="/home/*/VirtualBox VMs" \
	--exclude="*.box" \
	--exclude="${target}" \
	${excludes} \
	/ "${target}/${date}/"

sudo rm -f "${target}/current"
sudo ln -s "${target}/${date}" "${target}/current"

