#!/usr/bin/env python3
import sys,json

for line in sys.stdin.read().split("\n"):
    try:
        print(json.dumps(
            json.loads(line),
            sort_keys=True,
            indent=4
        ).replace("\\n","\n"))
    except Exception:
        print(line)

