#!/usr/bin/env python3

#
# A first attempt at a simple GTK application, use this to view JSON data in a
# graphical environment... just keep the dataset small.  Big files blow things
# up at the moment.
#

import sys,json
from gi.repository import Gtk

class LabelWindow(Gtk.Window):

    def __init__(self, path):

        Gtk.Window.__init__(self, title="Label Example")
        
        hbox = Gtk.Box(spacing=10)
        label = Gtk.Label(json.dumps(json.loads(open(path).read()), indent=4))
        hbox.pack_start(label, True, True, 0)
        label.set_selectable(True)

        self.add(hbox)



if __name__ == "__main__":

    if not len(sys.argv) == 2:
        print("Usage json-viewer.py <filename.json>")
        sys.exit(1)

    window = LabelWindow(sys.argv[1])
    window.connect("delete-event", Gtk.main_quit)
    window.show_all()
    Gtk.main()

