#!/usr/bin/env python

import glob
import os
import sys

if not len(sys.argv) == 2:
    print("Usage: linksequential /path/to/source/")
    sys.exit(1)

i = 0
for f in sorted(glob.glob(os.path.join(sys.argv[1], "*"))):
    i += 1
    os.symlink(f, "{:010}.png".format(i))

