#!/usr/bin/env python3

#
# This isn't ready yet.
#

import sys

contracted = sys.argv[1]
if "::" in contracted:
  replacements = []
  segments = len(contracted.split(":"))
  while segments < 8:
    replacements.append("0000")
    segments += 1
  contracted.replace("::", ":".join(replacements))

ip = ""
for segment in contracted.split(":"):
  ip += "0" * (4-len(segment)) + segment
print(ip)
#print(".".join([c for c in reversed(ip)]) + ".ip6.arpa")

