#!/usr/bin/env python3

"""
    "smart" grep.  This script does what grep does, but strips out the stuff
    you never want to see, like anything in the .svn, .git, or .hg
    directories, or a .pyc file.

    Handy tip: it supports regular expressions!
"""

import sys
from re import sub,match

arg = ""
try:
    arg = sys.argv[1]
except:
    pass

while True:

    line = sys.stdin.readline()

    if not line:
        break

    if ".pyc" not in line and not match(r".*\.(svn|git|hg|idea)(\/.*|$)", line):
        print(sub(r"(%s)" % (arg), "\033[1;31m\g<1>\033[0m", line), end=""),
