#!/usr/bin/env python3

"""
	"smart" grep.  This script does what grep does, but strips out the stuff
	you never want to see, like anything in a .svn directory, or a .pyc file.
"""

import sys
from re import sub

while True:

	line = sys.stdin.readline()

	if not line:
		break

	if ".pyc" not in line and ".svn" not in line:
		print(sub(r"%s" % (sys.argv[1]), "\033[1;31m%s\033[0m" % sys.argv[1], line), end=""),
