#!/usr/bin/env python3

import os
import subprocess
import random
import time

source = "{}/Pictures/Wallpaper".format(os.environ.get("HOME"))
target = "{}/.wallpaper".format(os.environ.get("HOME"))
walls = []


class Wallpaper(object):

    SLEEP_TIME = 60  # Seconds

    SOURCE = "{}/Pictures/Wallpaper".format(os.environ.get("HOME"))
    TARGET = "{}/.wallpaper".format(os.environ.get("HOME"))

    def __init__(self):
        
        self.walls = []
        self.populate()

        if not os.path.exists(self.TARGET):
            print(
                "This is the first time running wallpaperator, so we're creating "
                "a symlink at {} and telling GNOME to use it for "
                "wallpaper.".format(target)
            )
            self.set();
            subprocess.Popen("gsettings set {} picture-uri 'file://{}'".format(
                "org.gnome.desktop.background", target), shell=True)
            time.sleep(self.SLEEP_TIME)

    def populate(self):
        self.walls = [os.path.join(self.SOURCE, f) for f in os.listdir(self.SOURCE)]
        random.shuffle(self.walls)

    def set(self):
        subprocess.Popen(
        "ln -sf '{}' {}".format(self.walls.pop(), target), shell=True)

    def loop(self):
        while True:
            if not self.walls:
                self.populate()
            self.set()
            time.sleep(self.SLEEP_TIME)

if __name__ == "__main__":
    Wallpaper().loop()

